# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

Conciliacao_dados
"""

import pandas as pd

def carregar_dados():
    try:
        sistema = pd.read_csv('sistema.csv')
        corretora = pd.read_csv('corretora.csv')
        return sistema, corretora
    except Exception as e:
        print(f"Erro ao carregar arquivos: {e}")
        return None, None

def conciliar_dados(sistema, corretora):
    comparacao = sistema.merge(corretora, on='cliente', suffixes=('_sistema', '_corretora'))

    divergencias = comparacao[comparacao['valor_sistema'] != comparacao['valor_corretora']]

    return comparacao, divergencias

def gerar_relatorio(divergencias):
    if divergencias.empty:
        print("Nenhuma divergência encontrada.")
    else:
        print("Divergências encontradas:")
        print(divergencias)
        divergencias.to_csv('relatorio_divergencias.csv', index=False)

def main():
    sistema, corretora = carregar_dados()

    if sistema is not None and corretora is not None:
        comparacao, divergencias = conciliar_dados(sistema, corretora)
        gerar_relatorio(divergencias)

if __name__ == "__main__":
    main()